version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-docker-app
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend-docker-app
    ports:
      - "3000:3000"
